### ISSUE TITLE
Unable to delete an address on iPhone when an address is selected

### ISSUE THREAD

**Issue by CharlotteHinton** [ServiceInnovationLab/FSD#186]
As a user
When I've typed in an address on an iPhone 4s or SE and selected the correct address, I'm now unable to delete the address to select a new one. On Safari

**Comment by JacOng17** [comment]
Waiting for a phone to test on.

**Comment by CharlotteHinton** [comment]
@JacOng17 is this still outstanding, we can check with Sibby on borrowing hers if this hasn't happened.

**Comment by dlouise64** [comment]
@CharlotteHinton I will test this, I have an iphone I can use :)

**Comment by JacOng17** [comment]
This bug is not unique to iPhone 4s/SE, it is something that seems to be across all browsers.

**Comment by lamorrison** [comment]
It seems that on any platform when an address suggestion has been selected you can no longer edit the address value (but you can select and delete the entire contents of the field). This makes sense, because we only want to let the users search for real addresses which actually exist and are associated with a latitude and longitude.

I'm implementing a quick solution which is to have the 'Delete' and 'Backspace' keys clear the address suggestion - the user experience feels quite nice to me.

**Comment by sarahneeson** [comment]
@choirboy07 tested this remotely on his iPhone 8 (? - apologies Paul, I can't remember what kind you have).
His comment is:  _"deleting an address is still problematic. You can click into the selected address, click again and use "select all" to cut it out. [But] you cannot backspace delete the address."_

**Comment by choirboy07** [comment]
iPhone XR I think.

Paul
________________________________
