### ISSUE TITLE
Question about keyword searching

### ISSUE THREAD

**Issue by sarahneeson** [ServiceInnovationLab/FSD#248]
I have an example of a search where the results are not as I would expect.  

The search is 
Category: Parents and Caregivers
Topic or organisation: "Open Home".  
[Link to search](https://family.services.govt.nz/#/?category=Parents%20and%20Caregivers&keyword=Open%20Home&radius=25 )

The results include many providers with the name "Open Home Foundation", which is great.  

_However,_ I can't follow the logic about how the results are ordered.  
Some of the Open Home listings appear at the top.  Others are scattered further down the results, as far down as 43rd/50 position. 

I'm guessing that the ranking is affected by both the category (Parents and Caregivers) and the keywords (Open Home).  I would have thought that the results that have the keywords "Open Home" next to each other would be ranked the highest

**Question: Is that the expected behaviour?**
If not, is it possible to achieve this kind of ranking, or unlikely?

**Comment by lamorrison** [comment]
Hi Sarah, just wanted to leave a note to say I've looked at this quickly and it will need more investigation. You're right to think that the ranking is being effected by the category 'parents and caregivers'. 

We added the category to the database query to get better results when no keywords are given (when you just click on a category filter), but it might be better to stop using the category if there are keywords present. The results should be similar to what you see if you search for 'open home' without any category selected. That's a fairly quick change for us to make if you'd like to try it out.

Looking a little deeper, the search results for 'open home' in particular are affected by the way the search server is set up. It doesn't know that the title is more important than any other text so results which say 'open' and 'home' a lot in the body will get a higher ranking than things which say 'open home' once in the title. I looked into fixing this previously (boosting the title field) and found some documentation of how it should be possible but didn't have time to test it out because I was focusing on location searching at the time.

If I have more time to work on this I'd recommend an 'investigate search field boosting' task as a high priority because it could improve the ranking of results quite a lot.
