### ISSUE TITLE
Q: Why is Kapiti not available in the list of locations we can select?

### ISSUE THREAD

**Issue by Br3nda** [ServiceInnovationLab/FSD#266]

**Comment by Br3nda** [comment]
Initial team response:
In the address finder? it's controlled by someone else and it probably doesn't include Kāpiti in their region?

We'd need to look into this to confirm this is the problem.

**Comment by lamorrison** [comment]
The address finder API we use for address suggestions uses street, suburb, city, and region as its levels of granularity. It seems like Kapiti would fall in between their records for suburbs/cities (like Otaki) or the small number of national regions (probably Wellington for the Kapiti region). The API reference page is here: https://addressfinder.nz/api/nz/location/autocomplete/

**Comment by lamorrison** [comment]
This question also relates to a change between the original FSD system and this one - In the original system each provider was tagged with a region (and I guess Kapiti was one of them) which was used to filter the search.

The new system doesn't filter by region directly, but you can search in a radius from the centre of any location recognised by the address suggestion API - compare `WHERE region = 'Kapiti'` to `distance_between(provider_coordinates, user_coordinates) < 5km`

One option would be for site users to get used to searching near townships rather than in regions, which should give the same kinds of results.

Another option is to bring back the region filtering from the original version. The region field is still available on each record, and we could filter it the same way we filter for categories in the new FSD UI

**Comment by sarahneeson** [comment]
Thanks for looking into this for us @Br3nda and @lamorrison.  I wondered if it were an API thing.  

Including region from the FSD data source is an option, but (correct me if I'm wrong @choirboy07) probably not one we want to look into at this stage.  Agree that this would make the search cluttered and it might not be immediately obvious to someone why some locations show up in "Start typing an address" and others only appear under "Select a region".

**Comment by choirboy07** [comment]
Hi, this was originally for services near me - so I'm reluctant to put the region/district stuff in - leave as is and see what feedback is like.

**Comment by Br3nda** [comment]
Let's close this and re-open if there's need to further action
