### ISSUE TITLE
Display of Provider Purpose field

### ISSUE THREAD

**Issue by Br3nda** [ServiceInnovationLab/FSD#267]
Can we truncate the display of provider purpose?  Field can take max 1000 characters.  We’d like to see a max of 300 in the results on Find Whanau Support search

**Comment by Br3nda** [comment]
@lamorrison is this started? @JacOng17 has time to look at it.

**Comment by lamorrison** [comment]
I've had a look at how the search results are displayed and I think I've got a good solution for displaying longer provider purpose fields. Here's what I understand the problem to be:
- Long text is a problem on mobile but not desktop
- Long text is a problem in the search results list but not on the service details page

I've made a change so that in the mobile search results list only, the provider purpose section has a maximum height and it will scroll if the text overflows, like this:
<img width="356" alt="Screen Shot 2019-05-29 at 13 04 16" src="https://user-images.githubusercontent.com/33472821/58522176-3c598500-8213-11e9-88be-b1c10ef52272.png">

I've also changed the display of the provider purpose slightly so that it will respect any line breaks which are in the source data. You can see it in the image above - it's broken into paragraphs. Most of the provider purposes are just a single block of text, but I think this is an improvement.

I've also changed the display of the classifications at the bottom of that image so that there's a space in between the classifications (it was `YS,BFC` but now is `YS, BFC`)

If you'd still prefer to truncate the text rather than have it scroll that's a super easy change to make now that I've tidied up the code a bit. You can let me know now or in future after you've had a chance to use this version.

**Comment by sarahneeson** [comment]
Hi @lamorrison 
Thanks so much for looking into this issue for us!  Paul's just stepped away from his desk, so these are just my own thoughts.
The concept of a scrolling provider purpose sounds interesting to me, and I agree it could potentially resolve the issue for mobile users (without disadvantaging desktop users, which I'm guessing is your point).

Would it be possible to have a play with this solution in real life?

I definitely endorse the extra space to make the classifications easy to read!

@choirboy07 - your thoughts?
Here's the current layout, if you want to compare with Lyall's screenshot.

![Kapiti Youth Support](https://user-images.githubusercontent.com/34259860/58522908-5ea0d200-8216-11e9-8d46-53feeaa4e414.jpg)

**Comment by sarahneeson** [comment]
Oh gosh, that screenshot came through giant sized.  Apologies!

Paul has had a brief look, and is keen on seeing this solution too.  Sounds really good :)

**Comment by choirboy07** [comment]
The scrolling is working once you tap in the provider Purpose commentary - also the more details button is back so cool.

Not sure if the scroll within scroll is causing the "sliding" across the mobile screens - it's really hard to replicate this issue.

If it is the "new scroll" then I'd prefer to truncate the provider details field (and this is consistent with what we do on the website in Summary Results).
