### ISSUE TITLE
Bug: back button on mobiles

### ISSUE THREAD

**Issue by Br3nda** [ServiceInnovationLab/FSD#268]
To replicate

Load search page: family.services.govt.nz
Select category (eg. Youth Services).  Results display.
Select phone/browser back button
Expected result: blank search
Actual result: Category continues to be selected, but search summary states “0 results”

**Comment by lamorrison** [comment]
Released to UAT.

Keyword and category have been added to the React state (that's just an implementation detail), both should be tracked properly now through any number of back and forward navigations.

**Comment by sarahneeson** [comment]
Looks good @Br3nda and @lamorrison.  

Only comment on the fix is that (for the initial test scenario above) is you have to tap the screen to remove the light highlight/border on the Youth Service category.  

But that's small beans!  The page no longer displays zero results and the prompt "Make a search or choose a category above" should make it clear to people that they aren't looking at search results now. 

![Light highlight](https://user-images.githubusercontent.com/34259860/58850666-aa0a2300-86e3-11e9-811a-1716da7d85d2.jpg)

**Comment by choirboy07** [comment]
Agree with Sarah - small beans and if you are starting a new search you would tap the screen by default)
