### ISSUE TITLE
Add cucumber to circle-ci

### ISSUE THREAD

**Issue by mischa-s** [ServiceInnovationLab/FSD#94]

**Comment by lamorrison** [comment]
This is on hold because the Cucumber/Selenium tests aren't reliable enough at the moment. Particularly for the tests involving the address suggestions, they have a small chance of failing due to timing/network issues which don't reflect a problem in the code. As such, adding the cucumber tests into the CI pipeline would just introduce intermittent failures which would hold us up.

This could be resolved once we have a license key for the address finder which works in a test environment (I believe we have a production key which is tied to the production domain name)

In the mean time, cucumber tests can be run manually by developers from the command line.
